//
//  R.swift
//  InspectionTool
//
//  Created by Dan Leonard on 3/1/18.
//
//  This file is autogenerated by ResourceGenerator.swift
//  Check out the project @ https://github.com/MacMeDan/Locolization
//
// `R` represents Resource a common practace used in other development enviroments.
//

import Foundation

enum R {

	/** Abandoned Deal */
	static var abandonedDeal = {
		NSLocalizedString("abandonedDeal", comment: "Abandoned Deal")}()

	/** Add Dealer */
	static var addDealer = {
		NSLocalizedString("addDealer", comment: "Add Dealer")}()

	/** Add Note */
	static var addNote = {
		NSLocalizedString("addNote", comment: "Add Note")}()

	/** Additional Image %lu */
	static var additionalImageLu = {
		NSLocalizedString("additionalImageLu", comment: "Additional Image %lu")}()

	/** Address */
	static var address = {
		NSLocalizedString("address", comment: "Address")}()

	/** Address Line 2 */
	static var addressLine2 = {
		NSLocalizedString("addressLine2", comment: "Address Line 2")}()

	/** Advanced Filtering */
	static var advancedFiltering = {
		NSLocalizedString("advancedFiltering", comment: "Advanced Filtering")}()

	/** All Regions */
	static var allRegions = {
		NSLocalizedString("allRegions", comment: "All Regions")}()

	/** All Statuses */
	static var allStatuses = {
		NSLocalizedString("allStatuses", comment: "All Statuses")}()

	/** Apply Filters */
	static var applyFilters = {
		NSLocalizedString("applyFilters", comment: "Apply Filters")}()

	/** Appraised Value */
	static var appraisedValue = {
		NSLocalizedString("appraisedValue", comment: "Appraised Value")}()

	/** Are you sure? */
	static var areYouSure = {
		NSLocalizedString("areYouSure", comment: "Are you sure?")}()

	/** Arrived */
	static var arrived = {
		NSLocalizedString("arrived", comment: "Arrived")}()

	/** Arrived Date */
	static var arrivedDate = {
		NSLocalizedString("arrivedDate", comment: "Arrived Date")}()

	/** Authenticating */
	static var authenticating = {
		NSLocalizedString("authenticating", comment: "Authenticating")}()

	/** Automatic */
	static var automatic = {
		NSLocalizedString("automatic", comment: "Automatic")}()

	/** Bad Credentials */
	static var badCredentials = {
		NSLocalizedString("badCredentials", comment: "Bad Credentials")}()

	/** BOS Awaiting */
	static var bosAwaiting = {
		NSLocalizedString("bosAwaiting", comment: "BOS Awaiting")}()

	/** BOS Completed */
	static var bosCompleted = {
		NSLocalizedString("bosCompleted", comment: "BOS Completed")}()

	/** BOS History */
	static var bosHistory = {
		NSLocalizedString("bosHistory", comment: "BOS History")}()

	/** BOS Not Approved */
	static var bosNotApproved = {
		NSLocalizedString("bosNotApproved", comment: "BOS Not Approved")}()

	/** Burn */
	static var burn = {
		NSLocalizedString("burn", comment: "Burn")}()

	/** Buyer Signature* */
	static var buyerSignature = {
		NSLocalizedString("buyerSignature", comment: "Buyer Signature*")}()

	/** City */
	static var city = {
		NSLocalizedString("city", comment: "City")}()

	/** City/State/Zip */
	static var citystatezip = {
		NSLocalizedString("citystatezip", comment: "City/State/Zip")}()

	/** Clean */
	static var clean = {
		NSLocalizedString("clean", comment: "Clean")}()

	/** Clear Filters */
	static var clearFilters = {
		NSLocalizedString("clearFilters", comment: "Clear Filters")}()

	/** Collect Signatures */
	static var collectSignatures = {
		NSLocalizedString("collectSignatures", comment: "Collect Signatures")}()

	/** Color */
	static var color = {
		NSLocalizedString("color", comment: "Color")}()

	/** Component does not apply */
	static var componentDoesNotApply = {
		NSLocalizedString("componentDoesNotApply", comment: "Component does not apply")}()

	/** Component is acceptable */
	static var componentIsAcceptable = {
		NSLocalizedString("componentIsAcceptable", comment: "Component is acceptable")}()

	/** Component is unacceptable */
	static var componentIsUnacceptable = {
		NSLocalizedString("componentIsUnacceptable", comment: "Component is unacceptable")}()

	/** Component needs further review */
	static var componentNeedsFurtherReview = {
		NSLocalizedString("componentNeedsFurtherReview", comment: "Component needs further review")}()

	/** Confirm */
	static var confirm = {
		NSLocalizedString("confirm", comment: "Confirm")}()

	/** Create */
	static var create = {
		NSLocalizedString("create", comment: "Create")}()

	/** Date */
	static var date = {
		NSLocalizedString("date", comment: "Date")}()

	/** Date Created */
	static var dateCreated = {
		NSLocalizedString("dateCreated", comment: "Date Created")}()

	/** Dealer Address */
	static var dealerAddress = {
		NSLocalizedString("dealerAddress", comment: "Dealer Address")}()

	/** * denotes preferred account */
	static var denotesPreferredAccount = {
		NSLocalizedString("denotesPreferredAccount", comment: "* denotes preferred account")}()

	/** Displacement */
	static var displacement = {
		NSLocalizedString("displacement", comment: "Displacement")}()

	/** Driver Name */
	static var driverName = {
		NSLocalizedString("driverName", comment: "Driver Name")}()

	/** Driver Phone */
	static var driverPhone = {
		NSLocalizedString("driverPhone", comment: "Driver Phone")}()

	/** Drivetrain */
	static var drivetrain = {
		NSLocalizedString("drivetrain", comment: "Drivetrain")}()

	/** Edit Inspection */
	static var editInspection = {
		NSLocalizedString("editInspection", comment: "Edit Inspection")}()

	/** Edit Shipment Details */
	static var editShipmentDetails = {
		NSLocalizedString("editShipmentDetails", comment: "Edit Shipment Details")}()

	/** Edit Shipment Vehicles */
	static var editShipmentVehicles = {
		NSLocalizedString("editShipmentVehicles", comment: "Edit Shipment Vehicles")}()

	/** Edit Title */
	static var editTitle = {
		NSLocalizedString("editTitle", comment: "Edit Title")}()

	/** Edit Vehicles */
	static var editVehicles = {
		NSLocalizedString("editVehicles", comment: "Edit Vehicles")}()

	/** Email */
	static var email = {
		NSLocalizedString("email", comment: "Email")}()

	/** End: */
	static var end = {
		NSLocalizedString("end", comment: "End:")}()

	/** Engine Size */
	static var engineSize = {
		NSLocalizedString("engineSize", comment: "Engine Size")}()

	/** Error */
	static var error = {
		NSLocalizedString("error", comment: "Error")}()

	/** Fail */
	static var fail = {
		NSLocalizedString("fail", comment: "Fail")}()

	/** First Inspection */
	static var firstInspection = {
		NSLocalizedString("firstInspection", comment: "First Inspection")}()

	/** Fixed */
	static var fixed = {
		NSLocalizedString("fixed", comment: "Fixed")}()

	/** Front */
	static var front = {
		NSLocalizedString("front", comment: "Front")}()

	/** Full Inspection PDF */
	static var fullInspectionPdf = {
		NSLocalizedString("fullInspectionPdf", comment: "Full Inspection PDF")}()

	/** Full Purchase */
	static var fullPurchase = {
		NSLocalizedString("fullPurchase", comment: "Full Purchase")}()

	/** Initial */
	static var initial = {
		NSLocalizedString("initial", comment: "Initial")}()

	/** Inspection Overview */
	static var inspectionOverview = {
		NSLocalizedString("inspectionOverview", comment: "Inspection Overview")}()

	/** Inspection Summary */
	static var inspectionSummary = {
		NSLocalizedString("inspectionSummary", comment: "Inspection Summary")}()

	/** Inspection Tool */
	static var inspectionTool = {
		NSLocalizedString("inspectionTool", comment: "Inspection Tool")}()

	/** Inspector */
	static var inspector = {
		NSLocalizedString("inspector", comment: "Inspector")}()

	/** Inspector Name */
	static var inspectorName = {
		NSLocalizedString("inspectorName", comment: "Inspector Name")}()

	/** Insurance Classification */
	static var insuranceClassification = {
		NSLocalizedString("insuranceClassification", comment: "Insurance Classification")}()

	/** Last known location */
	static var lastKnownLocation = {
		NSLocalizedString("lastKnownLocation", comment: "Last known location")}()

	/** Last Modified */
	static var lastModified = {
		NSLocalizedString("lastModified", comment: "Last Modified")}()

	/** Loading */
	static var loading = {
		NSLocalizedString("loading", comment: "Loading")}()

	/** Loading Vehicles... */
	static var loadingVehicles = {
		NSLocalizedString("loadingVehicles", comment: "Loading Vehicles...")}()

	/** Logout */
	static var logout = {
		NSLocalizedString("logout", comment: "Logout")}()

	/** Make */
	static var make = {
		NSLocalizedString("make", comment: "Make")}()

	/** Manager */
	static var manager = {
		NSLocalizedString("manager", comment: "Manager")}()

	/** Manual */
	static var manual = {
		NSLocalizedString("manual", comment: "Manual")}()

	/** Mark Arrived */
	static var markArrived = {
		NSLocalizedString("markArrived", comment: "Mark Arrived")}()

	/** Mark in Transit */
	static var markInTransit = {
		NSLocalizedString("markInTransit", comment: "Mark in Transit")}()

	/** Mileage */
	static var mileage = {
		NSLocalizedString("mileage", comment: "Mileage")}()

	/** Model */
	static var model = {
		NSLocalizedString("model", comment: "Model")}()

	/** N/A */
	static var na = {
		NSLocalizedString("na", comment: "N/A")}()

	/** NADA Clean Trade */
	static var nadaCleanTrade = {
		NSLocalizedString("nadaCleanTrade", comment: "NADA Clean Trade")}()

	/** Name */
	static var name = {
		NSLocalizedString("name", comment: "Name")}()

	/** Needs Attention */
	static var needsAttention = {
		NSLocalizedString("needsAttention", comment: "Needs Attention")}()

	/** New Vehicle Information */
	static var newVehicleInformation = {
		NSLocalizedString("newVehicleInformation", comment: "New Vehicle Information")}()

	/** No */
	static var no = {
		NSLocalizedString("no", comment: "No")}()

	/** No Inspector */
	static var noInspector = {
		NSLocalizedString("noInspector", comment: "No Inspector")}()

	/** No Price */
	static var noPrice = {
		NSLocalizedString("noPrice", comment: "No Price")}()

	/** Notes */
	static var notes = {
		NSLocalizedString("notes", comment: "Notes")}()

	/** Odometer */
	static var odometer = {
		NSLocalizedString("odometer", comment: "Odometer")}()

	/** Odometer Disclosure */
	static var odometerDisclosure = {
		NSLocalizedString("odometerDisclosure", comment: "Odometer Disclosure")}()

	/** OK */
	static var ok = {
		NSLocalizedString("ok", comment: "OK")}()

	/** Options */
	static var options = {
		NSLocalizedString("options", comment: "Options")}()

	/** Other */
	static var other = {
		NSLocalizedString("other", comment: "Other")}()

	/** Other Classification */
	static var otherClassification = {
		NSLocalizedString("otherClassification", comment: "Other Classification")}()

	/** Paid */
	static var paid = {
		NSLocalizedString("paid", comment: "Paid")}()

	/** Parts Replaced/Repaired */
	static var partsReplacedrepaired = {
		NSLocalizedString("partsReplacedrepaired", comment: "Parts Replaced/Repaired")}()

	/** Parts Replaced/Repairs* */
	static var partsReplacedrepairs = {
		NSLocalizedString("partsReplacedrepairs", comment: "Parts Replaced/Repairs*")}()

	/** Password */
	static var password = {
		NSLocalizedString("password", comment: "Password")}()

	/** Payment */
	static var payment = {
		NSLocalizedString("payment", comment: "Payment")}()

	/** Payment Requested */
	static var paymentRequested = {
		NSLocalizedString("paymentRequested", comment: "Payment Requested")}()

	/** Pending */
	static var pending = {
		NSLocalizedString("pending", comment: "Pending")}()

	/** Phone */
	static var phone = {
		NSLocalizedString("phone", comment: "Phone")}()

	/** Photo Library */
	static var photoLibrary = {
		NSLocalizedString("photoLibrary", comment: "Photo Library")}()

	/** Please Wait */
	static var pleaseWait = {
		NSLocalizedString("pleaseWait", comment: "Please Wait")}()

	/** Preferred */
	static var preferred = {
		NSLocalizedString("preferred", comment: "Preferred")}()

	/** Purchase Price */
	static var purchasePrice = {
		NSLocalizedString("purchasePrice", comment: "Purchase Price")}()

	/** Quick Pay */
	static var quickPay = {
		NSLocalizedString("quickPay", comment: "Quick Pay")}()

	/** Reason */
	static var reason = {
		NSLocalizedString("reason", comment: "Reason")}()

	/** Reinspection */
	static var reinspection = {
		NSLocalizedString("reinspection", comment: "Reinspection")}()

	/** Reject */
	static var reject = {
		NSLocalizedString("reject", comment: "Reject")}()

	/** Reject Inspection? */
	static var rejectInspection = {
		NSLocalizedString("rejectInspection", comment: "Reject Inspection?")}()

	/** Rejected */
	static var rejected = {
		NSLocalizedString("rejected", comment: "Rejected")}()

	/** Request Payment */
	static var requestPayment = {
		NSLocalizedString("requestPayment", comment: "Request Payment")}()

	/** Reset */
	static var reset = {
		NSLocalizedString("reset", comment: "Reset")}()

	/** Retake Images */
	static var retakeImages = {
		NSLocalizedString("retakeImages", comment: "Retake Images")}()

	/** Retry */
	static var retry = {
		NSLocalizedString("retry", comment: "Retry")}()

	/** Review BOS */
	static var reviewBos = {
		NSLocalizedString("reviewBos", comment: "Review BOS")}()

	/** Salvage */
	static var salvage = {
		NSLocalizedString("salvage", comment: "Salvage")}()

	/** Save */
	static var save = {
		NSLocalizedString("save", comment: "Save")}()

	/** Saved Photos */
	static var savedPhotos = {
		NSLocalizedString("savedPhotos", comment: "Saved Photos")}()

	/** Search */
	static var search = {
		NSLocalizedString("search", comment: "Search")}()

	/** Search Everywhere */
	static var searchEverywhere = {
		NSLocalizedString("searchEverywhere", comment: "Search Everywhere")}()

	/** Search Processes */
	static var searchProcesses = {
		NSLocalizedString("searchProcesses", comment: "Search Processes")}()

	/** Search Shipments */
	static var searchShipments = {
		NSLocalizedString("searchShipments", comment: "Search Shipments")}()

	/** Searching */
	static var searching = {
		NSLocalizedString("searching", comment: "Searching")}()

	/** Select an Account */
	static var selectAnAccount = {
		NSLocalizedString("selectAnAccount", comment: "Select an Account")}()

	/** Select Area */
	static var selectArea = {
		NSLocalizedString("selectArea", comment: "Select Area")}()

	/** Select Vehicle */
	static var selectVehicle = {
		NSLocalizedString("selectVehicle", comment: "Select Vehicle")}()

	/** Seller */
	static var seller = {
		NSLocalizedString("seller", comment: "Seller")}()

	/** Seller Signature* */
	static var sellerSignature = {
		NSLocalizedString("sellerSignature", comment: "Seller Signature*")}()

	/** Send to Supplier */
	static var sendToSupplier = {
		NSLocalizedString("sendToSupplier", comment: "Send to Supplier")}()

	/** Shipment Details */
	static var shipmentDetails = {
		NSLocalizedString("shipmentDetails", comment: "Shipment Details")}()

	/** Shipment Filters */
	static var shipmentFilters = {
		NSLocalizedString("shipmentFilters", comment: "Shipment Filters")}()

	/** Shipment Information */
	static var shipmentInformation = {
		NSLocalizedString("shipmentInformation", comment: "Shipment Information")}()

	/** Shipment No - %@ */
	static var shipmentNo = {
		NSLocalizedString("shipmentNo", comment: "Shipment No - %@")}()

	/** Shipment Status */
	static var shipmentStatus = {
		NSLocalizedString("shipmentStatus", comment: "Shipment Status")}()

	/** Shipments */
	static var shipments = {
		NSLocalizedString("shipments", comment: "Shipments")}()

	/** Shipping */
	static var shipping = {
		NSLocalizedString("shipping", comment: "Shipping")}()

	/** Shipping From */
	static var shippingFrom = {
		NSLocalizedString("shippingFrom", comment: "Shipping From")}()

	/** Shipping To */
	static var shippingTo = {
		NSLocalizedString("shippingTo", comment: "Shipping To")}()

	/** State */
	static var state = {
		NSLocalizedString("state", comment: "State")}()

	/** Status - %@ */
	static var status = {
		NSLocalizedString("status", comment: "Status - %@")}()

	/** Submit */
	static var submit = {
		NSLocalizedString("submit", comment: "Submit")}()

	/** Supplier */
	static var supplier = {
		NSLocalizedString("supplier", comment: "Supplier")}()

	/** Supplier Number */
	static var supplierNumber = {
		NSLocalizedString("supplierNumber", comment: "Supplier Number")}()

	/** Supplying Location */
	static var supplyingLocation = {
		NSLocalizedString("supplyingLocation", comment: "Supplying Location")}()

	/** Take photo */
	static var takePhoto = {
		NSLocalizedString("takePhoto", comment: "Take photo")}()

	/** Title */
	static var title = {
		NSLocalizedString("title", comment: "Title")}()

	/** Title Back Image */
	static var titleBackImage = {
		NSLocalizedString("titleBackImage", comment: "Title Back Image")}()

	/** Title Classification */
	static var titleClassification = {
		NSLocalizedString("titleClassification", comment: "Title Classification")}()

	/** Title Front Image */
	static var titleFrontImage = {
		NSLocalizedString("titleFrontImage", comment: "Title Front Image")}()

	/** Title History */
	static var titleHistory = {
		NSLocalizedString("titleHistory", comment: "Title History")}()

	/** Title PDF */
	static var titlePdf = {
		NSLocalizedString("titlePdf", comment: "Title PDF")}()

	/** To Reinspect @ ASM Shop */
	static var toReinspectAsmShop = {
		NSLocalizedString("toReinspectAsmShop", comment: "To Reinspect @ ASM Shop")}()

	/** Total Units */
	static var totalUnits = {
		NSLocalizedString("totalUnits", comment: "Total Units")}()

	/** Trim */
	static var trim = {
		NSLocalizedString("trim", comment: "Trim")}()

	/** Trim/Series */
	static var trimseries = {
		NSLocalizedString("trimseries", comment: "Trim/Series")}()

	/** Unable to log in */
	static var unableToLogIn = {
		NSLocalizedString("unableToLogIn", comment: "Unable to log in")}()

	/** Unauthorized */
	static var unauthorized = {
		NSLocalizedString("unauthorized", comment: "Unauthorized")}()

	/** Update */
	static var update = {
		NSLocalizedString("update", comment: "Update")}()

	/** Username */
	static var username = {
		NSLocalizedString("username", comment: "Username")}()

	/** Vehicle Approved */
	static var vehicleApproved = {
		NSLocalizedString("vehicleApproved", comment: "Vehicle Approved")}()

	/** Vehicle Import */
	static var vehicleImport = {
		NSLocalizedString("vehicleImport", comment: "Vehicle Import")}()

	/** Vehicle Information */
	static var vehicleInformation = {
		NSLocalizedString("vehicleInformation", comment: "Vehicle Information")}()

	/** Vehicle Pending Approval */
	static var vehiclePendingApproval = {
		NSLocalizedString("vehiclePendingApproval", comment: "Vehicle Pending Approval")}()

	/** Vehicle Search */
	static var vehicleSearch = {
		NSLocalizedString("vehicleSearch", comment: "Vehicle Search")}()

	/** Warning */
	static var warning = {
		NSLocalizedString("warning", comment: "Warning")}()

	/** Water Recovery */
	static var waterRecovery = {
		NSLocalizedString("waterRecovery", comment: "Water Recovery")}()

	/** Year */
	static var year = {
		NSLocalizedString("year", comment: "Year")}()

	/** Your changes will be lost */
	static var yourChangesWillBeLost = {
		NSLocalizedString("yourChangesWillBeLost", comment: "Your changes will be lost")}()

	/** Zip Code */
	static var zipCode = {
		NSLocalizedString("zipCode", comment: "Zip Code")}()

}
