//
//  stringFinder.swift
//  Localizer
//
//  Created by Dan Leonard on 3/15/18.
//  Copyright © 2018 MacMeDan. All rights reserved.
//
//
// The purpose of this class it to find strings in a file and add them to the Localizeable.strings file
//  input: File
//  Output:
//      The input file with strings replaced with R.camelCased where strings were
//      Autogenerated case in Resources.swift
//      Autogenerated entry in Loalisable.strings
//

import Foundation

// Search all swift files within the directory
let fileManager = FileManager.default
let enumerator = fileManager.enumerator(atPath: CommandLine.arguments[1])

while let element = enumerator?.nextObject() as? String {
    if element.hasSuffix("swift") { // check only swift files
        findUnlocalisedStrings(fromFilePath: element)
    }
}



