//
//  ResourceGenerator.swift
//  Localizer
//
//  Created by Dan Leonard on 3/6/18.
//  Copyright © 2018 MacMeDan. All rights reserved.
//

import Foundation

class ResourceGenerator {
    
    func generate() {
        let newValues = Array(NSDictionary(contentsOf: urlToLocalizable).flatMap{$0}!).sorted{($0.0 as! String) < ($1.0 as! String)}

        let staticFunctions = newValues.map {
            """

            \t/** \(($1 as! String)) */
            \tstatic var \($0) = { NSLocalizedString("\($0)", comment: "\(($1 as! String).exscapeNewLine)") }()

            """
            }.joined()

        let contents = """
        //
        //  R.swift
        //  InspectionTool
        //
        //  Created by Dan Leonard on 3/1/18.
        //
        //  This file is autogenerated by \((#file as NSString).lastPathComponent)
        //  Check out the project @ https://github.com/MacMeDan/Localizer
        //
        // `R` represents Resource a common practace used in other development enviroments.
        //

        import Foundation

        enum R {
        \(staticFunctions)
        }

        """

        writeData(contents, path: resouceURL) { _ in
            numberOfUnlocalisedStrings += 1
        }
    }
}


func writeData( _ newData: String, path: URL, completion:((String) -> Void)) {
    do {
        try newData.write(to: path, atomically: true, encoding: .utf8)
        print("🤯 Converted \(numberOfUnlocalisedStrings) \(path.lastPathComponent)")
        completion("Sucsess Writing to path: \(path)")
    } catch {
        completion(error.localizedDescription)
    }
}





