//
//  Strings.swift
//  Localizer
//
//  Created by Dan Leonard on 3/6/18.
//  Copyright © 2018 MacMeDan. All rights reserved.
//

import Foundation

extension String {


    /// Makes a sentence camel cased variable name -> makesASentenceCamelCasedVariableName
    var camelCased: String {
        var componets = self.components(separatedBy: " ")
        //Filter invalid charicters before adding capitalization
        componets = componets.compactMap{ $0.validChars == "" ? nil : $0.validChars }
        guard let first = componets.first?.lowercased() else { return "" }
        if componets.count == 1 { return "\(first)"}
        // Limits the lenght of a autogenerated name to 10 words
        let remaining = componets.count > 10 ? componets[1...10].compactMap{ $0.capitalized }.joined() : componets.dropFirst().compactMap{ $0.capitalized }.joined()
        return "\(first)\(remaining)"
    }

    var validChars: String {
        return String(describing: filter {
            String($0).rangeOfCharacter(from: .alphanumerics) != nil
        })
    }

    var exscapeNewLine: String {
        return self.replacingOccurrences(of: "\n", with: "\\n")
    }

}
